import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar/Navbar'
const inter = Inter({ subsets: ['latin'] })
import getCurrentUser from '@/app/actions/getCurrentUser';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className="min-h-screen">
       {/* @ts-ignore */}
        <Navbar currentUser={currentUser} />
        {children}
        </body>
    </html>
  )
}
